# Generated by Django 4.1.3 on 2022-12-04 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_alter_bid_amount'),
        ('user', '0006_review_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='client',
            new_name='employer',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='bidder',
            new_name='freelancer',
        ),
        migrations.RemoveField(
            model_name='review',
            name='subject',
        ),
        migrations.AddField(
            model_name='review',
            name='on_budget',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='job.job'),
        ),
        migrations.AddField(
            model_name='review',
            name='timely',
            field=models.BooleanField(default=False),
        ),
    ]
