# Generated by Django 4.1.3 on 2022-12-04 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0007_rename_client_review_employer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_employer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_frelancer', to=settings.AUTH_USER_MODEL),
        ),
    ]
